### ISSUE TITLE
Unable to use "either::serde_untagged", instructions unclear

### ISSUE THREAD

**Issue by nyvs** [bluss/either#53]
I am providing a reprex for the use of either::serde_untagged.
I have not been able to use this feature, because 
this line:
 `#[serde(with = "either::serde_untagged")]`
fails to compile, and I cannot figure out why.
```
//main.rs
use serde::{Serialize, Deserialize};
use either::Either;

fn main() {
    #[derive(Serialize, Deserialize, Debug)]
    #[serde(transparent)]
    struct IntOrString {
        #[serde(with = "either::serde_untagged")]
        inner: Either<Vec<String>, u8>
    };
}
```

```
//Cargo Toml deps
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
either = "1.6.1"
```
I am grateful for any help

**Comment by cuviper** [comment]
You also need the "serde" feature for either:

```toml
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
either = { version = "1.6.1", features = ["serde"] }
```
